### ISSUE TITLE
First public version

### ISSUE THREAD

**Issue by daniwebCH** [AmoebeLabs/swiss-army-knife-card-manual#1]
Hi Marco,
looks like very promising what you are doing.
Of course this is not an Issue ;-)

Could you give some estimate of when you will feel ready for a public version ?

Thanks

**Comment by AmoebeLabs** [comment]
Thanks!

An estimate for public release is still difficult. Currently, about 30 ppl are testing the card in a closed beta.
I have around 30 issues at this moment, of which 15 should be fixed before the public release as some of them result in breaking changes. And that is not something I want for the first release!

I'm currently preparing beta3 for release, and anticipate that I need a beta4 to test all the fixed issues. So around 1-2 months probably for public release.

I guess you found this repository via the HA Material 3 themes? 

I also want HAM3 and SAK to be compatible at public release. That should not be a lot of work but makes the examples from the start compatible with light/dark themes.

Marco.

**Comment by eladore** [comment]
Marco!
I am a ux designer for many many years too. Your work is absolutely incredible... Stay on that track....

**Comment by AmoebeLabs** [comment]
Thanx @eladore !

Nice to read my work is appreciated :smile:

**Comment by spencerthayer** [comment]
Excited to play with this but I do not see Swiss Army Knife available in HACS yet. "No repositories found matching your filter."

**Comment by eladore** [comment]
It is not released yet. I would also appreciate a public beta =)

**Comment by daniwebCH** [comment]
> Thanks!
> 
> An estimate for public release is still difficult. Currently, about 30 ppl are testing the card in a closed beta. I have around 30 issues at this moment, of which 15 should be fixed before the public release as some of them result in breaking changes. And that is not something I want for the first release!
> 
> I'm currently preparing beta3 for release, and anticipate that I need a beta4 to test all the fixed issues. So around 1-2 months probably for public release.
> 
> I guess you found this repository via the HA Material 3 themes?
> 
> I also want HAM3 and SAK to be compatible at public release. That should not be a lot of work but makes the examples from the start compatible with light/dark themes.
> 
> Marco.

As SW developer I understand that you prefer to have something more stable, especially from the potential breaking changes and manual activities.
It is not always so easy to decide the right moment to give it public, because from that moment you are also exposed to the questions/issues coming  ;-)

> 
> I guess you found this repository via the HA Material 3 themes?
Yes, from the "Some real-world screenshots:".

**Comment by eladore** [comment]
It is worth to wait and buy him a big cup of coffee afterwards :-)

**Comment by AmoebeLabs** [comment]
> As SW developer I understand that you prefer to have something more stable, especially from the potential breaking changes and manual activities. It is not always so easy to decide the right moment to give it public, because from that moment you are also exposed to the questions/issues coming ;-)

It's not that I want to release a perfect product, it's more the breaking changes I don't want right after the first release. I know from beta testing that it takes some time to understand the card and create your own designs. Breaking changes do not play nice with all that work.

It also means double work for me, as I have to change the documentation!

> It is not released yet. I would also appreciate a public beta =)

I could start with a release candidate in which at least all known breaking changes have been implemented. And then implement the remaining issues for a 1.0 release. That way I can release it sooner.

According to some simple statistics (Github counters), around 400 ppl have accessed the documentation. No idea how many of these are returning visitors, but it is not anymore some 'secret' card 😄 

I will update this issue from time to time!

**Comment by eladore** [comment]
Yes that sounds great! Don't feel pushed... at the end we all don't want to redo all our work because of breaking changes...

**Comment by AmoebeLabs** [comment]
No worries 😉 

I get sidetracked sometimes. A few weeks ago I wanted to fix some styling issues and ended up creating  the Material 3 Themes for Home Assistant 😵‍💫 

So, some sort of focus isn’t wrong 😑. 
There is documentation with enough examples to work with. And of course I’m curious about what others can make with this card…

**Comment by ad-ha** [comment]
Hi,

This really looks awesome and I am just waiting to get to try it. Looks like you will be getting me to rebuild my whole lovelace panels 😄 

Looking forward for the public beta (release candidate) and help as possible.

Btw, I am trying the M3 themes now as well 👍 

Cheers and great work.

**Comment by NdR91** [comment]
Hello Marco,

Your work is really awesome.
I'm playing with yaml dashboard since some years, and this is one of the coolest I ever seen.

Can't wait for the public beta!
Let me know if you need one more tester for the closed one =P

**Comment by wernerhp** [comment]
How do I join the Beta?

**Comment by daniwebCH** [comment]
Hi Marco,
could you give us a short status update ;-)

Thanks

**Comment by scaarup** [comment]
Will we ever get to try this out??

**Comment by 1337Reaper** [comment]
> Will we ever get to try this out??

I see minor updates to the project every few days with the last one being done 4 days ago. I was hoping to be able to get into the beta but @AmoebeLabs didn’t respond via Discord, unfortunately.

**Comment by wernerhp** [comment]
> Will we ever get to try this out??

The author of the repo doesn't owe anyone anything. He's has spent hours working on this and has gone through difficult personal times (read his story).  He doesn't need to make any of this available to anyone.  We can offer to help develop and test this and if he chooses for you to help that's great. Asking for updates or imptient questions is very disheartening.

**Comment by 1337Reaper** [comment]
@wernerhp While I agree that they could have commented in a more polite manner, I don’t think it’s asking too much for an update every now and again. Updates are part of the dev cycle and saying they’re “disheartening” is going a bit too far, IMO.

**Comment by wernerhp** [comment]
@1337Reaper You are of course entitled to have your opinion, however I've never seen any terms or any "dev cycle" that states "any person who chooses to make their code freely available and without charge must, within a reasonable time, provide updates on the state of said code's development progress and release dates to anyone who from time to time requests such an update.  Updates are a courtesy and the free giving of the code is a gift we should appreciate more.  Have you published anything open source before?

**Comment by 1337Reaper** [comment]
@wernerhp No because I can’t stand to work with people with these kinds of opinions. Even a little “hey this is still being worked on” update is normal.

**Comment by AmoebeLabs** [comment]
Yo Guys & Girls,

Over the past six months, I've had to put all my energy into collaborating with the Dutch Tax Authorities to settle my sister's estate. It was exhausting, frustrating and at times very painful. Even with the help of two notaries.

As a result, around March of this year, I became more or less detached from the world around me. I promised my sister and myself to finish everything in 18 months, and that was all that mattered to me.

A few weeks ago I finally got the verdict through 11 blue envelopes, and I'm waiting for a few more. So I'm almost done executing my sister's will!

Fortunately, after receiving those blue envelopes, I was hit really hard by the flu or a cold. I can never tell the exact difference. The 6-month "conversation" with the DTA turned out to be not that good for my overall health...

I am now back on my feet again. 

My first step was to check all my email and social channels. I was surprised to find over 200 (!!!) posts from all over the world about the Swiss Army Knife Custom Map and its themes of Material 3!

I process them as fast as I can 😄 

The second thing I'm going to do is prepare for a public beta. So there will be more unresolved issues, but at least everyone can play with the card. The documentation should help you understand the card's capabilities and design your own cards. You won't often find such documentation with beta software, I guess. At least that was finished on time 🥳 

I believe the public beta will help me - as it helped me before while I was working on it - to focus on the future. 

Remember the past and an image of the future. Or as my sister used to say: "You can't change the past, so don't focus on the past, focus on the road ahead."

Marco.

**Comment by 1337Reaper** [comment]
@AmoebeLabs I’m sorry to hear about all the trouble you’ve had getting closure on everything. I truly appreciate the update and I look forward to contributing once the public beta opens.

**Comment by AmoebeLabs** [comment]
> @AmoebeLabs I’m sorry to hear about all the trouble you’ve had getting closure on everything. I truly appreciate the update and I look forward to contributing once the public beta opens.

No worries. Sometimes life's a bitch. 

Can't set an exact date yet for the release, but it won't be long.

**Comment by NdR91** [comment]
Thank you for your update Marco, this is much appreciated.

Can't wait to joint the Public Beta, i'm following each code changing you are doing and it seems to be really cool.

Thank you again!

**Comment by AmoebeLabs** [comment]
An update on the work I have to do for the public release (Release Candidate v0.9.0-rc1).

I curated the issues that address breaking changes that were postponed during the beta to avoid hindering the beta testers. But as you all understand, they must be resolved before the public release to avoid a lot more users having to change everything...

So that's my challenge for the upcoming weeks 😄 

And yes, some issues date back to 2020. At that time I spent around 40 hours/week on this card and hoped to release it in 2021...

![image](https://user-images.githubusercontent.com/7996307/171994185-4869938d-27e4-4f10-b6b7-2fb242dd27af.png)

The history bug is not mandatory to solve, so I might skip that one. But the rest involves configuration changes. I might just change the configuration, and postpone the functionality though.

For starters, I made changes to the structure & setup for HACS compliance, and that seems to be ok as a first step:

![image](https://user-images.githubusercontent.com/7996307/171994432-26154f0c-928c-4c52-b95b-d6eba13a6f8d.png)

But that was the easiest issue to be fair!

**Comment by AmoebeLabs** [comment]
I managed to change the implementation of some of the issues to "none breaking", meaning I can postpone them!

Me happy and of course everybody waiting for a release 🎈 

Current status as of today (2022.06.10):
![image](https://user-images.githubusercontent.com/7996307/173020587-90e55347-dc7f-457a-85a7-651fa4829f3b.png)

Work on the actions/tap_action is progressing well. Not too complicated, but just a lot of work because I also have to change all the examples and used decluttering and Swiss Army Knife templates!

A PR is made to be included in HACS. That one is waiting for 3 reviews before it will be merged. I will make a beta.4 release as HACS requires a real release present and not only pre-releases.

The v1.0.0-rc.1 version will be the actual release!

That's it for now.

**Comment by AmoebeLabs** [comment]
## Current status as of today (2022.06.15):

- Refactoring the actions is done, and all examples still work 😄 
- Currently working on the other issues.
- As you can see the number of tasks for the preparation has increased: I needed more things to do, but it is going well!

![image](https://user-images.githubusercontent.com/7996307/173812467-98dca3f3-9e29-4f3d-bae0-e217aa4b0eb7.png)

### The manuals have been moved to more logical subdomains:
- https://swiss-army-knife-card-manual.amoebelabs.com
- https://material3-themes-manual.amoebelabs.com

Redirects are set up, so the old subdomains are forwarded to the new ones. Google and Bing are notified and are moving the sites internally for their search results.

### Still waiting for HACS...
Merging PRs for HACS can take 4-6 weeks. The oldest PR is 3 weeks old, so it might take another 1 to 3 weeks before this card is available in HACS. I will just have to wait before I can test the installation...

I hope that if I fixed the last real issue, that HACS merges the PR, and that I can release the card soon after that!

**Comment by AmoebeLabs** [comment]
![](https://cdn.buymeacoffee.com/uploads/cover_images/2022/03/031b514a6d380b1356dd1c2fd0447399.png@2560w_0e.webp)
## Current status as of today (2022.06.18):
- All preparations that could be done, are done!
- I have to wait for the HACS merge, as some details are not yet clear about the exact installation. So that is something I have to test after the card is available in HACS. The documentation for the installation is also waiting for this point to finish.
There is a small chance that I have to make some installation/structure changes.
- Current state is saved as beta.6

![image](https://user-images.githubusercontent.com/7996307/174454378-b7ad6d54-bc64-417d-9292-30f3c933628a.png)

The draft topic for the forums is also ready, so I can't do anything more at this moment than to go downstairs and enjoy (hopefully) the Formula 1 qualification in Canada and the race tomorrow 🍁

**Comment by wernerhp** [comment]
You can add a custom repository to HACS if you want to test before it is merged.
![image](https://user-images.githubusercontent.com/2578772/174455662-60e5760a-1477-43fa-a296-efaf74c163ec.png)
![image](https://user-images.githubusercontent.com/2578772/174455669-c04b271f-aa76-4f65-b4d0-93565e77db4d.png)
https://github.com/AmoebeLabs/swiss-army-knife-card/releases/tag/v0.9.0-beta.6
![image](https://user-images.githubusercontent.com/2578772/174455684-6f179a21-8f54-40a2-b179-70c6877c5bc2.png)
![image](https://user-images.githubusercontent.com/2578772/174455690-3b7f0333-9b4a-4067-9624-1cdfc3fb96f6.png)
![image](https://user-images.githubusercontent.com/2578772/174455695-2421be89-53e7-44e6-8fc0-e504886f2ac7.png)

**Comment by AmoebeLabs** [comment]
> You can add a custom repository to HACS if you want to test before it is merged. 

Werner,

Yes I did test it that way. And the results are not exactly what I would expect reading the documentation. That's why I asked Ludeeus what to do, and depending on the answer, I might have to change something.

**Comment by AmoebeLabs** [comment]
The card has been merged into HACS, so I try to finalize Github and the documentation today before the Formula 1 race 🎉

**Comment by NdR91** [comment]
Great Marco! Thank you!

**Comment by AmoebeLabs** [comment]
> Great Marco! Thank you!

Thanx. If feels like a big step for me, given the background and all the work I put into this card and the Material 3 themes.

I just created the Github v1.0.0-rc.1a release and created a big TS for the forums, which I will publish soon.

**Comment by AmoebeLabs** [comment]
I guess I can close this issue now with the first public version released today!

**Comment by ad-ha** [comment]
Great Marco. Thank you for this. Will now have a try.
